config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  post "/links", to: "links#create"
  get "/links", to: "links#index"
  get '/reveal/:id', to: "links#reveal", as: :reveal
  get '/hide/:id', to: "links#hide", as: :hide
  get "/s/:short_url", to: "links#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :short_url, presence: true, uniqueness: true
  validates :original_url, presence: true, format: { with: /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/i }

  def full_short_url
    "http://localhost:3000/s/#{short_url}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @link = Link.new
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def create
    shortener = Shortener.new(link_params[:original_url])
    @link = shortener.create_link
    if @link.persisted?

    else
      render 'error.js.erb'
    end
  end

  def show
    link = Link.find_by(short_url: params[:short_url])
    redirect_link = link.original_url
    unless redirect_link[/\Ahttp:\/\//] || redirect_link[/\Ahttps:\/\//]
      redirect_link = "http://#{redirect_link}"
    end

    redirect_to redirect_link
  end

  def index
    @links = Link.all.paginate(page: params[:page], per_page: 5)
  end

  def reveal
    @link = Link.find(params[:id])
  end

  def hide
    @link = Link.find(params[:id])
  end

  private

  def link_params
    params.require(:link).permit(:original_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="p-5">
    <%= link_to "All Links", links_path, class: "btn btn-info mb-2" %>
    <div class="card">
      <div class="card-body">
        <%= form_with(model: @link, local: false) do |form| %>
          <h5 class="card-title">Enter a URL to shorten</h5>
          <%= form.text_field :original_url, class: 'form-control', placeholder: 'Enter a URL to shorten' %>
          <%= form.submit 'Generate', class: 'btn btn-primary mt-2' %>
        <% end %>
      </div>
      <div id="show-url"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_error.html.erb
<div class="card-footer">
  <div class="alert alert-danger">
    <b>Error:</b> <%= message %>
  </div>
</div>

app/views/links/_link.html.erb
<div class="card-footer">
  <div class="alert alert-success">
    <b>Shortened URL:</b> <%= link %>
    <hr />
    <small>copy this url into the browser to see the original website</small>
  </div>
</div>

app/views/links/create.js.erb
var element = document.getElementById('show-url');
var html = "<%= j render 'link', link: @link.full_short_url %>"
element.innerHTML = html;

app/views/links/error.js.erb
var element = document.getElementById('show-url');
var html = "<%= j render 'error', message: 'the given URL is not valid' %>"
element.innerHTML = html;

app/views/links/hide.js.erb
var element = document.getElementById("link-<%= @link.id %>");
var hide_btn = document.getElementById("hide-btn-<%= @link.id %>");
var reveal_btn = document.getElementById("reveal-btn-<%= @link.id %>");
element.innerHTML = "<%= @link.full_short_url %>";
hide_btn.style.display = 'none';
reveal_btn.style.display = 'block';

app/views/links/index.html.erb
<div class="container">
  <div class="p-5">
    <div><%= link_to "Home", root_path, class: "btn btn-primary mb-2" %></div>
    <div class="digg_pagination">

      <% @links.each do |link| %>
        <div class="card">
          <div class="card-body">
            <span id="link-<%= link.id %>"><%= link.full_short_url %></span>
            <%= link_to "Original", reveal_path(id: link.id), remote: true, class: "btn btn-warning", style: "float: right", id: "reveal-btn-#{link.id}" %>
            <%= link_to "Shortened", hide_path(id: link.id), remote: true, class: "btn btn-warning", style: "float: right; display: none", id: "hide-btn-#{link.id}" %>
          </div>
        </div>
      <% end %>
      <%= will_paginate @links %>
    </div>
  </div>
</div>

app/views/links/reveal.js.erb
var element = document.getElementById("link-<%= @link.id %>");
var hide_btn = document.getElementById("hide-btn-<%= @link.id %>");
var reveal_btn = document.getElementById("reveal-btn-<%= @link.id %>");
element.innerHTML = "<%= @link.original_url %>";
hide_btn.style.display = 'block';
reveal_btn.style.display = 'none';